CREATE TABLE "DRAGON" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "NAME" VARCHAR(50) NOT NULL ,
    "COUNTOFHEADS" INTEGER NOT NULL,
    "PRICEFORDAY" INTEGER NOT NULL
 );

 CREATE TABLE "CUSTOMER" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "NAME" VARCHAR(50) NOT NULL,
    "PHONE" VARCHAR(20) NOT NULL,
    "ADDRESS" VARCHAR(50) NOT NULL
 );

 CREATE TABLE "LEASE" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "DRAGON" BIGINT,
    "CUSTOMER" BIGINT,
    "STARTDATE" DATE NOT NULL ,
    "ENDDATE" DATE NOT NULL ,
    "PRICE" INTEGER NOT NULL
 );
